# Generated by Django 3.2.4 on 2021-08-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='stripe_pid',
            field=models.CharField(default='', max_length=254, unique=True),
        ),
    ]
