# Generated by Django 3.2.4 on 2021-06-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='stripe_pid',
            field=models.CharField(default='', max_length=254),
        ),
    ]
