# Generated by Django 3.2.4 on 2021-08-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_auto_20210812_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='genre',
            field=models.CharField(choices=[('', 'Genre'), ('Fiction', 'Fiction'), (
                'Non-fiction', 'Non-fiction'), ('Unknown', 'Unknown')], default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(upload_to='public/story_images/'),
        ),
    ]
