# Generated by Django 3.2.4 on 2021-06-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(blank=True, choices=[('Fiction', 'Fiction'), ('Non-fiction', 'Non-fiction'), (None, 'Select a genre')], default=None, max_length=50)),
                ('title', models.CharField(max_length=254)),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(max_length=5000)),
                ('image', models.ImageField(blank=True, upload_to='story_images/')),
                ('pdf', models.FileField(upload_to='story_pdfs/')),
                ('featured', models.BooleanField(blank=True, default=False)),
                ('reading_time_mins', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
