# Generated by Django 3.2.4 on 2021-06-15 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_auto_20210614_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='genre',
            field=models.CharField(blank=True, choices=[('Fiction', 'Fiction'), ('Non-fiction', 'Non-fiction')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='reading_time_string',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
