# Generated by Django 3.2.4 on 2021-08-12 12:53

import custom_storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_auto_20210719_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='image_credit',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='story',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='story',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='story',
            name='genre',
            field=models.CharField(choices=[('Fiction', 'Fiction'), (
                'Non-fiction', 'Non-fiction'), ('Unknown', 'Unknown')], default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(
                storage=custom_storages.PublicFileStorage(), upload_to='story_images/'),
        ),
        migrations.AlterField(
            model_name='story',
            name='reading_time_mins',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='reading_time_string',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(default='', max_length=254),
        ),
    ]
