# Generated by Django 3.2.4 on 2021-06-15 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_auto_20210615_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='reading_time_string',
            field=models.CharField(default='Unknown', max_length=254),
        ),
    ]
