# Generated by Django 3.2.4 on 2021-08-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_auto_20210812_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='genre',
            field=models.CharField(choices=[('', 'Genre'), ('Fiction', 'Fiction'), (
                'Non-fiction', 'Non-fiction'), ('Unknown', 'Unknown')], default='', max_length=254),
        ),
    ]
