# Generated by Django 3.2.4 on 2021-06-15 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_alter_story_reading_time_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='genre',
            field=models.CharField(blank=True, choices=[('Fiction', 'Fiction'), ('Non-fiction', 'Non-fiction'), ('Unknown', 'Unknown'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='reading_time_string',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
