# Generated by Django 3.2.4 on 2021-08-18 18:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_alter_story_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='description',
            field=models.TextField(default='', validators=[django.core.validators.MaxLengthValidator(10000), django.core.validators.MinLengthValidator(50)]),
        ),
        migrations.AlterField(
            model_name='story',
            name='genre',
            field=models.CharField(choices=[('', 'Select genre'), ('Fiction', 'Fiction'), ('Non-fiction', 'Non-fiction'), ('Unknown', 'Unknown')], default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='story',
            name='reading_time_mins',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(60000), django.core.validators.MinValueValidator(1)]),
        ),
    ]
